### ISSUE TITLE
some thoughts...

### ISSUE THREAD

**Issue by vitaly-t** [shawndellysse/pg.promised#1]
> pg-promise is very full-featured and adds a lot to node-postgres but I wanted something much simpler.

I'm guessing, the reason you want something simpler is because you haven't written enough database transaction code. Once you get there, and start understanding just how complex it can get with a simple promise approach...

Also, one of the huge features you will miss out is the very powerful query formatting, compared to the very basic one in node-postgres.

Just a thought... :)

**Comment by sdellysse** [comment]
I meant no offense with that line, and you are right there are a lot of niceties in your lib, but adding that to a lib named `pg-promise` seems like a bit of a misnomer; I like libraries that do a little as needed and are easy to compose. 

If that functionality were separated out of the pg-promise lib, and the base was just like this, and everything else could be layered on on an as-needed basis, there would have been no reason for me to write this. ;-)

**Comment by vitaly-t** [comment]
Most of what's there was implemented as separate modules that can be used accordingly:
- query formatting
- sql file loading

They are all also indispensable for the library usage. I'm not sure how this is somehow a disadvantage, for the library being a complete solution.

**Comment by sdellysse** [comment]
Essentially it comes down to uncertainty. I know how node-postgres works. I know how it performs, I know what to expect of it. This lib is just an extraction from codebases of high-performance servers I've written. The issue with kitchen-sink libraries is that I don't know the performance characteristics.

I assume in order for pg-promise to do its query formatting there must be a parsing step where it scans the string for parsable tokens; I have no need of this in many projects. I get how it can be useful, but when you don't need it, the overhead of automatic features you don't use can get in the way. 

I see no reason for sql file loading to be part of the core "connect-to-the-db-and-run-queries" lib, as useful as it is. I do the same thing in most of my projects, and having `.sql` files is very nice. If it were another module that spat out functions that accepted a client connection instance, I'd use the hell out of it, but it shouldn't be part of the core lib.

Note that I'm not talking down about your project, it covers a much larger surface area than I'd like so I wrote this, and if anyone else can get use out of it then so be it.

**Comment by vitaly-t** [comment]
> Essentially it comes down to uncertainty

My library offers one of the best documentations out there, one that covers everything.

> I know how node-postgres works. I know how it performs, I know what to expect of it

Have a look at [Performance Boost](https://github.com/vitaly-t/pg-promise/wiki/Performance-Boost), you will understand where to concern yourself about the performance and where not.

> The issue with kitchen-sink libraries is that I don't know the performance characteristics.

To put it this way, 99% of time you are guaranteed to spend communicating requests to the server. The remaining 1% of what the library spends becomes relevant. After all, it is not an ORM, and so it doesn't have such an overhead.

> I assume in order for pg-promise to do its query formatting there must be a parsing step where it scans the string for parsable tokens; I have no need of this in many projects.

Don't use what you do not need. Although writing a db service without formatting queries isn't realistic.

> I see no reason for sql file loading to be part of the core "connect-to-the-db-and-run-queries" lib

Everyone is now using this feature, and people love it.  What to understand the advantage? - see [Query Files](https://github.com/vitaly-t/pg-promise#query-files), and then [pg-promise-demo](https://github.com/vitaly-t/pg-promise-demo), the way it is used there.

**Comment by sdellysse** [comment]
I'm not sure what you want out of this, I repeatedly state that I'm not shitting on your work but I needed something less than what your lib provides, and you respond that I do need it. It's not that I don't understand these features or think that no one would use them; I simply need the lightest-weight promise wrapper for pg possible.

I put the comparison in the readme to state why I wrote this simple wrapper instead of using your lib. It was not an attack on pg-promise, nor was it a condemnation. If you cannot understand why I would like a simple lib that just wraps node-postgres in promises, then I believe we are at an impasse.

**Comment by sdellysse** [comment]
Note: I apologize if my tone was harsh in the previous comment, it was not meant to be, I blame commenting before my morning coffee ;-)

**Comment by vitaly-t** [comment]
Well, this is my pre-coffee morning, and I opt to close the subject :)
